extends Node

var WORDS = ['abogado', 'aceite', 'áfrica', 'agente', 'agua', 'águila', 'aguja', 'agujero', 'aire', 'alemania', 'algodón', 
'alianza', 'alpes', 'ambulancia', 'américa', 'ángel', 'anillo', 'antártida', 'antorcha', 'araña', 'archivo', 'arco', 
'argentina', 'artículo', 'as', 'atlántida', 'azteca', 'baile', 'bala', 'ballena', 'banco', 'banda', 'baño', 'barco', 
'barra', 'batería', 'berlín', 'bermudas', 'bicho', 'blanco', 'bloque', 'boca', 'bola', 'bolsa', 'bomba', 'bosque', 
'bota', 'botella', 'botón', 'brazo', 'bruja', 'caballero', 'caballo', 'cabeza', 'cabina', 'cabo', 'cactus', 'cadena', 
'caja', 'cama', 'cámara', 'cambio', 'campana', 'campo', 'canal', 'canguro', 'canto', 'caña', 'capa', 'capital', 'caqui', 
'cara', 'caravana', 'carga', 'carrera', 'carro', 'carta', 'casco', 'casino', 'caza', 'cementerio', 'centauro', 'centro', 
'cervantes', 'checo', 'chocolate', 'choque', 'chuleta', 'científico', 'cinta', 'cinturón', 'círculo', 'clase', 'coche', 
'cocinero', 'coco', 'código', 'cola', 'cólera', 'columna', 'cometa', 'compás', 'concierto', 'conejo', 'contrabandista', 
'copa', 'corazón', 'corneta', 'corona', 'corredor', 'corriente', 'corte', 'cresta', 'cromo', 'cruz', 'cuadro', 'cuarto', 
'cubierta', 'cubo', 'cuchillo', 'cuello', 'cuerda', 'cuerno', 'cura', 'dama', 'delta', 'destino', 'día', 'diamante', 
'diana', 'diario', 'diente', 'dinosaurio', 'disco', 'don', 'dragón', 'duende', 'egipto', 'embajada', 'emperador', 'enano', 
'enfermedad', 'enfermera', 'enlace', 'escorpión', 'espacio', 'espía', 'estación', 'estadio', 'estado', 'estrella', 
'estudio', 'etiqueta', 'europa', 'extraterrestre', 'falda', 'fantasma', 'faro', 'ficha', 'fiesta', 'figura', 'flauta', 
'flecha', 'foso', 'francia', 'frente', 'fuego', 'fuente', 'fuerza', 'furgoneta', 'gancho', 'gato', 'genio', 'gigante', 
'golfo', 'golondrina', 'golpe', 'goma', 'góndola', 'gota', 'grado', 'granada', 'grano', 'grecia', 'grifo', 'guante', 
'guardia', 'guerra', 'gusano', 'helado', 'helicóptero', 'hielo', 'hierba', 'hoja', 'hollywood', 'horca', 'hospital', 
'hotel', 'iglesia', 'imán', 'india', 'índice', 'inglaterra', 'italia', 'jarra', 'judía', 'juicio', 'kiwi', 'ladrón', 
'lago ness', 'láser', 'látigo', 'lengua', 'león', 'libra', 'lima', 'limusina', 'línea', 'lista', 'llama', 'llave', 'lomo', 
'londres', 'luna', 'luz', 'maestro', 'magia', 'malta', 'mancha', 'mando', 'manga', 'mango', 'mano', 'manzana', 'mañana', 
'marca', 'marcha', 'marfil', 'masa', 'máscara', 'mazo', 'médico', 'mercurio', 'mesa', 'metro', 'méxico', 'micro', 
'microscopio', 'miedo', 'millonario', 'mina', 'misil', 'modelo', 'módulo', 'monitor', 'mono', 'mortero', 'moscú', 
'motor', 'muelle', 'muerte', 'muñeca', 'muro', 'naranja', 'nave', 'nieve', 'nilo', 'ninja', 'noche', 'nota', 'nudo', 
'nueva york', 'obra', 'ojo', 'ola', 'olimpo', 'ópera', 'orden', 'órgano', 'ornitorrinco', 'oro', 'oso', 'pala', 'palma', 
'pantalla', 'papel', 'paracaídas', 'pase', 'paso', 'pasta', 'pastel', 'pavo', 'pekín', 'película', 'pelotón', 'pendiente', 
'perro', 'pez', 'pico', 'pie', 'pieza', 'pila', 'piloto', 'pincho', 'pingüino', 'pinta', 'piña', 'pirámide', 'pirata', 
'pista', 'pistola', 'placa', 'plano', 'planta', 'plátano', 'playa', 'plomo', 'pluma', 'policía', 'polo', 'portada', 
'portero', 'potro', 'prensa', 'prima', 'princesa', 'puente', 'puerto', 'pulpo', 'pulso', 'punta', 'punto', 'radio', 
'rascacielos', 'ratón', 'rayo', 'red', 'regla', 'reina', 'reserva', 'revolución', 'rey', 'robot', 'rojo', 'roma', 'ronda', 
'rosa', 'ruleta', 'sable', 'sáhara', 'salsa', 'satélite', 'saturno', 'señal', 'serie', 'serpiente', 'sierra', 'silla', 
'sirena', 'sobre', 'soldado', 'submarinista', 'suerte', 'superhéroe', 'tabla', 'tableta', 'taco', 'tacto', 'talón', 
'tanque', 'tapa', 'tarde', 'teatro', 'teclado', 'telescopio', 'testigo', 'tiempo', 'tienda', 'tierra', 'tokio', 'topo', 
'torre', 'trama', 'tronco', 'tubería', 'tubo', 'unicornio', 'vacío', 'vado', 'vampiro', 'vela', 'veneno', 'venus', 
'vestido', 'vida', 'vidrio', 'viento', 'yema', 'zanahoria', 'zapato', 'acantilado', 'aceituna', 'admirador', 'alfiler', 
'allioli', 'alma', 'alumno', 'amazonas', 'amigo', 'aplicación', 'arroyo', 'aspiradora', 'astronauta', 'atlantis', 'átomo', 
'atrás', 'australia', 'avión', 'babosa', 'balanza', 'bandera', 'bar', 'basura', 'baya', 'beijing', 'bizcocho', 'bocina', 
'búfalo', 'calabaza', 'calcetín', 'camioneta', 'canadá', 'canarias', 'candado', 'capucha', 'célula', 'cepillo', 'césped', 
'cheque', 'chorro', 'ciclo', 'circulo', 'clave', 'club', 'cobre', 'colegio', 'columpio', 'combatiente', 'cómic', 
'compuesto', 'conductor', 'contrato', 'corbata', 'correo', 'cuadra', 'cuadrado', 'dado', 'disparo', 'dólar', 'embarazo', 
'enfermero', 'enterrador', 'entrenamiento', 'espejo', 'espia', 'factura', 'fecha', 'felicidad', 'fila', 'fosa', 'frío', 
'fruteria', 'garrapata', 'gas', 'gobernante', 'gorra', 'gracia', 'gráfico', 'gravedad', 'grillo', 'grua', 'halcón', 
'hechizo', 'herradura', 'hierro', 'himalaya', 'hora', 'huelga', 'hundir', 'jamón', 'juego', 'junta', 'júpiter', 'justo', 
'laboratorio', 'lámina', 'lavadora', 'limón', 'lugar', 'maletero', 'mamut', 'mandarina', 'mármol', 'martillo', 'menta', 
'mermelada', 'miel', 'mío', 'mosca', 'murciélago', 'niño', 'novela', 'nuez', 'objetivo', 'onda', 'otoño', 'palmera', 
'palo', 'pantalones', 'pared', 'parque', 'parte', 'partido', 'pato', 'pecho', 'personal', 'pescado', 'peseta', 'petróleo', 
'pi', 'piano', 'pincel', 'piscina', 'pizarra', 'plastilina', 'plataforma', 'polaco', 'polluelo', 'porcelana', 'portátil', 
'primavera', 'profesor', 'pulgar', 'raíz', 'rama', 'raqueta', 'redondo', 'reloj', 'ritmo', 'robin', 'roca', 'saco', 'sartén', 
'sello', 'sequía', 'servidor', 'shakespeare', 'sol', 'sombra', 'sorbete', 'suelo', 'tablero', 'taladro', 'tarjeta', 'tarta', 
'taza', 'templo', 'tenedor', 'ternero', 'tiburón', 'tornillo', 'traje', 'trébol', 'triángulo', 'tribunal', 'tropical', 
'uña', 'valla', 'ventilador', 'verde', 'vestir', 'veterinario', 'viaje', 'vínculo', 'volcán', 'vuelta', 'web', 'zebra']
